services:
  ib-gateway:
    build:
      context: .
      args:
        VNC_PASSWORD: $VNC_PASSWORD
    image: martinffx/ib-gateway-docker
    platform: linux/amd64
    env_file: .env
    environment:
      TWS_PORT: 4002
      VNC_PORT: 5900
    ports:
      - 4002:4002
      - 5900:5900
